# Language versions to run on
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
# Installing glpk solver
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq glpk-utils
# command to install dependencies
install: pip install .[dev]
# Test with pytest
script: pytest --cov=ormm
# Run codecov after success
after_success:
    - codecov
# Only email notifications on failure
notifications:
  email:
    on_success: never
    on_failure: always